blueprint:
  name: Time Activated Lights
  description: Turn on lights at a specific time.
  domain: automation

  input:
    time_entity:
      name: Time to trigger lights.
      description: Time to trigger lights.
      selector:
        time:

    light_target:
      name: Light to turn on when time is in.
      description: Lights to turn on when time is in.
      selector:
        target:
          entity:
            domain: light

mode: single
max_exceeded: silent

trigger:
  - platform: time
    at: !input time_entity
  - platform: homeassistant
    event: start

action:
  - service: light.turn_on
    target: !input light_target