blueprint:
  name: Time Activated Lights
  description: Turn on lights at a specific time.
  domain: automation

  input:
    time_entity:
      name: Time
      description: Time to trigger lights.
      default: "06:30:00"
      selector:
        time: {}

    light_target:
      name: Light
      description: Lights to turn on when time is correct.
      selector:
        target:
          entity:
            domain: light

mode: restart
max_exceeded: silent

variables:
  time_on: !input time_entity

trigger:
  - platform: time
    at: !input time_on

action:
  - service: light.turn_on
    target: !input light_target