blueprint:
  name: Time Activated Lights
  description: Turn on lights at a specific time.
  domain: automation

  input:
    time_on:
      name: Time to turn on lights.
      description: Time to turn on lights.
      default: '10:00:00'
      selector:
        time:

    time_off:
      name: Time to turn off lights.
      description: Time to turn off lights.
      default: '23:00:00'
      selector:
        time:

    light_target:
      name: Light to turn on when time is in.
      description: Lights to turn on when time is in.
      selector:
        target:
          entity:
            domain: light

variables:
  time_format: '%H:%M:%S'
  first_event: '{{ time_on if strptime(time_on,time_format).time() < strptime(time_off,time_format).time() else time_off }}'
  second_event: '{{ time_on if strptime(time_on,time_format).time() >= strptime(time_off,time_format).time() else time_off }}'

mode: single
max_exceeded: silent

trigger:
  - platform: time
    at: 
      - !input time_on
      - !input time_off

action:
  - choose:
    
    - conditions:
      - condition: template
        value_template:  '{{ now().time() >= strptime(first_event,time_format).time() and now().time() < strptime(second_event,time_format).time() }}'
    
      sequence:
        - service: 'light.{{ "turn_on" if first_event == time_on else "turn_off" }}'
          target: !input light_target
    
    default:
      - service: 'light.{{ "turn_on" if second_event == time_on else "turn_off" }}'
        target: !input light_target
    
