blueprint:
  name: Time Activated Lights
  description: Turn on lights at a specific time.
  domain: automation

  input:
    time_entity:
      name: Time to trigger lights.
      description: Time to trigger lights.
      default: '10:00:00'
      selector:
        time:

    light_target:
      name: Light to turn on when time is in.
      description: Lights to turn on when time is in.
      selector:
        target:
          entity:
            domain: light
    
    light_brightness:
      name: Specify how bright you want the light to be.
      description: Specify how bright you want the light to be.
      selector:
        number:
          min: 5
          max: 100
          unit_of_measure: '%'

mode: single
max_exceeded: silent

trigger:
  - platform: time
    at: !input time_entity
  - platform: homeassistant
    event: start

action:
  - service: light.turn_on
    target: !input light_target
    data:
      brightness: !input light_brightness